<?php

use Drupal\civiremote;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\user\UserInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function civiremote_user_insert(UserInterface $user): void {
  civiremote\User::onInsert($user);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function civiremote_user_update(UserInterface $user): void {
  /** @var \Drupal\user\UserInterface $original */
  $original = $user->original;
  if ($original->isBlocked() && !$user->isBlocked()) {
    civiremote\User::onUnblock($user);
  }
}

/**
 * Implements hook_user_login().
 */
function civiremote_user_login(UserInterface $account): void {
  civiremote\User::onLogin($account);
}

/**
 * Implements hook_entity_base_field_info().
 *
 * @return array<string, \Drupal\Core\Field\FieldDefinitionInterface>
 */
function civiremote_entity_base_field_info(EntityTypeInterface $entity_type): array {
  // Add a base field to the User entity for storing the CiviRFemote ID.
  $fields = [];

  if ($entity_type->id() === 'user') {
    $fields['civiremote_id'] = BaseFieldDefinition::create('string')
      ->setLabel(t('CiviRemote ID'))
      ->setDescription(t('The unique CiviRemote ID for the user in the connected CiviCRM.'))
      ->setDisplayOptions('view', [
        'label' => 'visible',
        'type' => 'string',
        'weight' => -5,
      ])
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('form', [
        'type' => 'string_textfield',
        'settings' => [
          'display_label' => TRUE,
        ],
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setRequired(FALSE);
  }

  return $fields;
}
