civiremote.settings:
  type: config_object
  mapping:
    cmrf_connector:
      type: string
      label: 'CiviMRF Connector'
    acquire_civiremote_id:
      type: boolean
      label: 'Acquire CiviRemote ID'
    match_blocked_users:
      type: boolean
      label: 'Match blocked users'
    match_on_unblock:
      type: boolean
      label: 'Acquire CiviRemote ID when unblocking user'
    match_on_login:
      type: boolean
      label: 'Acquire CiviRemote ID on login'
    match_on_login_exclude_roles:
      type: sequence
      label: 'Roles to exclude when matching on login'
      sequence:
        type: string
        label: 'Role'
    match_contact_mapping:
      type: sequence
      label: 'Parameter mapping'
      sequence:
        type: mapping
        label: 'Mapping of a Drupal user field to a CiviCRM contact field'
        mapping:
          user_field:
            type: string
            label: 'Drupal user field'
          contact_field:
            type: string
            label: 'CiviCRM contact field'
action.configuration.civiremote_match_contact_action:
  type: action_configuration_default
  label: 'CiviRemote: Match contact(s)'
action.configuration.civiremote_synchronise_roles_action:
  type: action_configuration_default
  label: 'CiviRemote: Synchronise CiviRemote roles'
