<?php
/*------------------------------------------------------------+
| CiviRemote - CiviCRM Remote Integration                     |
| Copyright (C) 2020 SYSTOPIA                                 |
| Author: J. Schuppe (schuppe@systopia.de)                    |
+-------------------------------------------------------------+
| This program is released as free software under the         |
| Affero GPL license. You can redistribute it and/or          |
| modify it under the terms of this license which you         |
| can read by viewing the included agpl.txt or online         |
| at www.gnu.org/licenses/agpl.html. Removal of this          |
| copyright header is strictly prohibited without             |
| written permission from the original author(s).             |
+-------------------------------------------------------------*/

use Drupal\Component\Utility\NestedArray;

/**
 * Implements hook_views_data_alter().
 */
function civiremote_event_views_data_alter(array &$data) {
  foreach ($data as $group => $fields) {
    if (strpos($group, 'cmrf_views_') === 0) {
      foreach ($fields as $field_name => $field_definition) {
        if (
          $field_definition['type'] == 2
          && !empty($field_definition['format'])
          && $field_definition['format'] == 'json'
        ) {
          // TODO: Implement as relationship or render as single field.
        }
      }
    }
  }
}

function civiremote_event_preprocess_form_element(&$variables) {
  $element = &$variables['element'];
  if (isset($element['#zebra_context'])) {
    $zebra_context = &drupal_static('civiremote_event_preprocess_form_element__container');
    if (!isset($zebra_context)) {
      $zebra_context = [];
    }
    $zebra = (isset($zebra_context[$element['#zebra_context']]) ? $zebra_context[$element['#zebra_context']] : 1);
    $variables['attributes']['class'][] = $zebra ? 'odd' : 'even';
    $zebra_context[$element['#zebra_context']] = (int)!$zebra;
  }
}

function civiremote_event_preprocess_form_element_label(&$variables) {
  $element = &$variables['element'];
  if (!empty($element['#attributes']['display_required'])) {
    $variables['required'] = $variables['required'] || $element['#attributes']['display_required'];
    unset($element['#attributes']['display_required']);
  }
}

function civiremote_event_preprocess_container(&$variables) {
  $element = &$variables['element'];
  if (
    isset($element['#zebra_context'])
    && isset($element['#array_parents'])
    && in_array('sessions', $element['#array_parents'], TRUE)
  ) {
    $zebra_context = &drupal_static('civiremote_event_preprocess_form_element__container');
    if (!isset($zebra_context)) {
      $zebra_context = [];
    }
    $zebra = (isset($zebra_context[$element['#zebra_context']]) ? $zebra_context[$element['#zebra_context']] : 1);
    $variables['attributes']['class'][] = $zebra ? 'odd' : 'even';
    $zebra_context[$element['#zebra_context']] = (int)!$zebra;
  }
}

function civiremote_event_preprocess_fieldset(&$variables) {
  $element = &$variables['element'];
  if (!empty($element['#label_attributes']['display_required'])) {
    $variables['required'] = $variables['required'] || $element['#label_attributes']['display_required'];
    unset($element['#label_attributes']['display_required']);
  }
}

function civiremote_event_preprocess_details(&$variables) {
  $element = &$variables['element'];
  if (!empty($element['#label_attributes']['display_required'])) {
    $variables['required'] = $variables['required'] || $element['#label_attributes']['display_required'];
    unset($element['#label_attributes']['display_required']);
  }
}

function civiremote_event_preprocess_textarea(&$variables) {
  $element = &$variables['element'];
  if (!empty($element['#label_attributes']['display_required'])) {
    $variables['required'] = $variables['required'] || $element['#label_attributes']['display_required'];
    unset($element['#label_attributes']['display_required']);
  }
}

function civiremote_event_theme($existing, $type, $theme, $path) {
  return [
    'cmrf_views_field_json_item__cmrf_views_civiremote_event_events__speakers' => [
      'base hook' => 'cmrf_views_field_json_item',
    ],
  ];
}
