<?php

/**
 * Implements hook_views_data_alter().
 */
function civiremote_event_views_data_alter(array &$data) {
  foreach ($data as $group => $fields) {
    if (strpos($group, 'cmrf_views_') === 0) {
      foreach ($fields as $field_name => $field_definition) {
        if (
          $field_definition['type'] == 2
          && !empty($field_definition['format'])
          && $field_definition['format'] == 'json'
        ) {
          // TODO: Implement as relationship or render as single field.
        }
      }
    }
  }
}

function civiremote_event_preprocess_form_element_label(&$variables) {
  $element = &$variables['element'];
  if (!empty($element['#attributes']['display_required'])) {
    $variables['required'] = $element['#attributes']['display_required'];
    unset($element['#attributes']['display_required']);
  }
}

function civiremote_event_preprocess_fieldset(&$variables) {
  $element = &$variables['element'];
  if (!empty($element['#label_attributes']['display_required'])) {
    $variables['required'] = $element['#label_attributes']['display_required'];
    unset($element['#label_attributes']['display_required']);
  }
}

function civiremote_event_preprocess_details(&$variables) {
  $element = &$variables['element'];
  if (!empty($element['#label_attributes']['display_required'])) {
    $variables['required'] = $element['#label_attributes']['display_required'];
    unset($element['#label_attributes']['display_required']);
  }
}

function civiremote_event_preprocess_textarea(&$variables) {
  $element = &$variables['element'];
  if (!empty($element['#label_attributes']['display_required'])) {
    $variables['required'] = $element['#label_attributes']['display_required'];
    unset($element['#label_attributes']['display_required']);
  }
}
